# Настройки ORM
datasource:
  default: ${APP_ENV}
  # Задаём базу данных, к которой будет происходить подключение
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./hexlet"
  production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: ${DATABASE_URL}
# Заполняем базу данных первоначальными данными
ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true

